name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker image tag
        id: docker-tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          fi

      - name: Build Docker image for multiple architectures
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository }}/exporter:${{ env.TAG }} --push .

      - name: Push Docker image to GHCR as ${{ env.TAG }}
        run: |
          # Image is already pushed as part of buildx build step.
          echo "Image pushed to GHCR with tag: ${{ env.TAG }}"
